In [1]:
3+5*4

23

In [2]:
weight_kg=60

In [3]:
weight_kg+60

120

In [4]:
weight_kg=60.0

In [5]:
weight_kg_text='weight in kilograms:'

In [6]:
print(weight_kg)

60.0


In [7]:
print(weight_kg_text,weight_kg)

weight in kilograms: 60.0


In [8]:
print('weight in pounds:',2.2*weight_kg)

weight in pounds: 132.0


In [9]:
import numpy


In [10]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [11]:
data = numpy.loadtxt(fname='inflammation-01.csv',delimiter=',')

In [12]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [13]:
print(type(data))

<class 'numpy.ndarray'>


In [14]:
print(data.dtype)

float64


In [15]:
print(data.shape)

(60, 40)


In [16]:
print('first value in data:', data[0,0])

first value in data: 0.0


In [18]:
print('middle value in data:',data[30,20])

middle value in data: 13.0


In [19]:
print(data[0:4,0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [20]:
print(data[5:10,0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [21]:
small = data[:3,36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [22]:
print(numpy.mean(data))

6.14875


In [23]:
import time
print(time.ctime())

Thu Jul 30 20:23:44 2020


In [24]:
maxval,minval,stdval = numpy.max(data), numpy.min(data),numpy.std(data)
print('maximum inflammation:', maxval)
print('minimum inflammation:',minval)
print('standard deviation:', stdval)

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [26]:
patient_0=data[0,:]
print('maximum inflammation for patient 0:', numpy.max(patient_0))

maximum inflammation for patient 0: 18.0
