In [1]:
3+5*4

23

In [2]:
weight_kg=60

In [3]:
weight_kg+60

120

In [4]:
weight_kg=60.0

In [5]:
weight_kg_text='weight in kilograms:'

In [6]:
print(weight_kg)

60.0


In [7]:
print(weight_kg_text,weight_kg)

weight in kilograms: 60.0


In [8]:
print('weight in pounds:',2.2*weight_kg)

weight in pounds: 132.0


In [9]:
import numpy


In [10]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [11]:
data = numpy.loadtxt(fname='inflammation-01.csv',delimiter=',')

In [12]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [13]:
print(type(data))

<class 'numpy.ndarray'>


In [14]:
print(data.dtype)

float64


In [15]:
print(data.shape)

(60, 40)


In [16]:
print('first value in data:', data[0,0])

first value in data: 0.0


In [18]:
print('middle value in data:',data[30,20])

middle value in data: 13.0


In [19]:
print(data[0:4,0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [20]:
print(data[5:10,0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [21]:
small = data[:3,36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [22]:
print(numpy.mean(data))

6.14875


In [23]:
import time
print(time.ctime())

Thu Jul 30 20:23:44 2020


In [24]:
maxval,minval,stdval = numpy.max(data), numpy.min(data),numpy.std(data)
print('maximum inflammation:', maxval)
print('minimum inflammation:',minval)
print('standard deviation:', stdval)

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [26]:
patient_0=data[0,:]
print('maximum inflammation for patient 0:', numpy.max(patient_0))

maximum inflammation for patient 0: 18.0


In [27]:
print('maximum inflammation for patient 2:',numpy.max(data[2,:]))

maximum inflammation for patient 2: 19.0


In [28]:
print(numpy.mean(data,axis=0))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


In [29]:
print(numpy.mean(data, axis=0).shape)

(40,)


In [30]:
print(numpy.mean(data, axis=1))

[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]


In [31]:
print(numpy.mean(data, axis=1).shape)

(60,)


In [32]:
print(data.shape)

(60, 40)


In [33]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [34]:
A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
